import { useRef } from 'react'
const About = () => {
    const aboutRef = useRef()

    // Scroll to About Page
    const handleAboutClick = () => {
        aboutRef.current.scrollIntoView({ behavior: 'smooth' })
    }

    return (
        <div className="content">
            <h1 ref={aboutRef}>HELLO! I'M DEREK YANG</h1>
            <h3>CONTACT ME</h3>
            <h3>DOWNLOAD RESUME</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis venenatis nisi, eget hendrerit urna. In sollicitudin commodo ipsum, nec suscipit felis maximus nec. Sed maximus, odio quis ultrices volutpat, felis mauris varius magna, ac consectetur tellus lorem ut tortor. Aenean a nisl quis ex auctor elementum sit amet ac erat. Ut aliquam augue vitae vulputate dictum. Aliquam mauris nulla, fringilla ac erat at, lacinia tempor ipsum. Nam blandit cursus magna, ac sodales risus tristique vitae. Proin hendrerit, lorem ac placerat aliquam, arcu ligula tristique ante, eu volutpat eros nisi ac quam. Morbi dui tortor, ultrices quis tempus et, ultricies non enim. Nullam sit amet ante in purus iaculis consectetur. Suspendisse id ipsum accumsan, vestibulum mauris vitae, mollis nisl. Quisque id justo tincidunt, commodo quam vel, vestibulum tortor. Nunc ipsum ante, posuere eu vulputate vel, varius sed massa. Ut a orci scelerisque, ornare magna id, faucibus arcu. Maecenas vitae ex lorem. Nam a nibh id ipsum vestibulum dapibus.

            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer nec porttitor ante. Proin vitae faucibus velit, in sollicitudin libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse lectus dolor, interdum elementum fringilla et, efficitur a libero. Etiam sit amet imperdiet nunc. Sed viverra magna vel lorem euismod, nec interdum lectus volutpat. Vestibulum lobortis non ex quis sagittis. Nunc volutpat eleifend tincidunt. Maecenas at imperdiet libero. Sed vulputate ligula in turpis suscipit gravida. Nam sit amet ornare mi. Donec fermentum aliquam arcu id ullamcorper. Nam sodales quis mi non lobortis.

            Quisque dictum purus ac eros scelerisque, et pulvinar ex sollicitudin. Nullam sit amet turpis felis. Sed dictum enim a ipsum fringilla sagittis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi sagittis facilisis orci et ullamcorper. Aenean hendrerit massa non lacus posuere dapibus. Curabitur vel placerat augue. Integer efficitur elit nec urna ornare tempor. Nullam eu rutrum lacus. Mauris porta tempus fermentum. Sed tristique lorem quis ipsum tempor dapibus. Cras quis nisi massa. Suspendisse ut sapien sollicitudin, laoreet sem ut, convallis mi.

            Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse sit amet ipsum non nisl laoreet facilisis. Nulla facilisi. Sed quis tristique eros. Proin sed tempor nulla. Nulla blandit facilisis tellus id pulvinar. Vivamus vel imperdiet dui, iaculis ultricies sapien.

            Duis finibus purus a enim consequat, nec vestibulum elit viverra. Quisque porta semper tellus, et tempus urna tincidunt sed. Fusce finibus congue sem, sed egestas dolor. Sed molestie magna vel turpis euismod ullamcorper. Nulla facilisis scelerisque lectus sit amet porttitor. Aenean elementum vehicula neque. In et nulla ac eros mattis ullamcorper sed non turpis. In convallis enim sed maximus molestie.
            </p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis venenatis nisi, eget hendrerit urna. In sollicitudin commodo ipsum, nec suscipit felis maximus nec. Sed maximus, odio quis ultrices volutpat, felis mauris varius magna, ac consectetur tellus lorem ut tortor. Aenean a nisl quis ex auctor elementum sit amet ac erat. Ut aliquam augue vitae vulputate dictum. Aliquam mauris nulla, fringilla ac erat at, lacinia tempor ipsum. Nam blandit cursus magna, ac sodales risus tristique vitae. Proin hendrerit, lorem ac placerat aliquam, arcu ligula tristique ante, eu volutpat eros nisi ac quam. Morbi dui tortor, ultrices quis tempus et, ultricies non enim. Nullam sit amet ante in purus iaculis consectetur. Suspendisse id ipsum accumsan, vestibulum mauris vitae, mollis nisl. Quisque id justo tincidunt, commodo quam vel, vestibulum tortor. Nunc ipsum ante, posuere eu vulputate vel, varius sed massa. Ut a orci scelerisque, ornare magna id, faucibus arcu. Maecenas vitae ex lorem. Nam a nibh id ipsum vestibulum dapibus.

            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer nec porttitor ante. Proin vitae faucibus velit, in sollicitudin libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse lectus dolor, interdum elementum fringilla et, efficitur a libero. Etiam sit amet imperdiet nunc. Sed viverra magna vel lorem euismod, nec interdum lectus volutpat. Vestibulum lobortis non ex quis sagittis. Nunc volutpat eleifend tincidunt. Maecenas at imperdiet libero. Sed vulputate ligula in turpis suscipit gravida. Nam sit amet ornare mi. Donec fermentum aliquam arcu id ullamcorper. Nam sodales quis mi non lobortis.

            Quisque dictum purus ac eros scelerisque, et pulvinar ex sollicitudin. Nullam sit amet turpis felis. Sed dictum enim a ipsum fringilla sagittis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi sagittis facilisis orci et ullamcorper. Aenean hendrerit massa non lacus posuere dapibus. Curabitur vel placerat augue. Integer efficitur elit nec urna ornare tempor. Nullam eu rutrum lacus. Mauris porta tempus fermentum. Sed tristique lorem quis ipsum tempor dapibus. Cras quis nisi massa. Suspendisse ut sapien sollicitudin, laoreet sem ut, convallis mi.

            Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse sit amet ipsum non nisl laoreet facilisis. Nulla facilisi. Sed quis tristique eros. Proin sed tempor nulla. Nulla blandit facilisis tellus id pulvinar. Vivamus vel imperdiet dui, iaculis ultricies sapien.

            Duis finibus purus a enim consequat, nec vestibulum elit viverra. Quisque porta semper tellus, et tempus urna tincidunt sed. Fusce finibus congue sem, sed egestas dolor. Sed molestie magna vel turpis euismod ullamcorper. Nulla facilisis scelerisque lectus sit amet porttitor. Aenean elementum vehicula neque. In et nulla ac eros mattis ullamcorper sed non turpis. In convallis enim sed maximus molestie.
            </p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis venenatis nisi, eget hendrerit urna. In sollicitudin commodo ipsum, nec suscipit felis maximus nec. Sed maximus, odio quis ultrices volutpat, felis mauris varius magna, ac consectetur tellus lorem ut tortor. Aenean a nisl quis ex auctor elementum sit amet ac erat. Ut aliquam augue vitae vulputate dictum. Aliquam mauris nulla, fringilla ac erat at, lacinia tempor ipsum. Nam blandit cursus magna, ac sodales risus tristique vitae. Proin hendrerit, lorem ac placerat aliquam, arcu ligula tristique ante, eu volutpat eros nisi ac quam. Morbi dui tortor, ultrices quis tempus et, ultricies non enim. Nullam sit amet ante in purus iaculis consectetur. Suspendisse id ipsum accumsan, vestibulum mauris vitae, mollis nisl. Quisque id justo tincidunt, commodo quam vel, vestibulum tortor. Nunc ipsum ante, posuere eu vulputate vel, varius sed massa. Ut a orci scelerisque, ornare magna id, faucibus arcu. Maecenas vitae ex lorem. Nam a nibh id ipsum vestibulum dapibus.

            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer nec porttitor ante. Proin vitae faucibus velit, in sollicitudin libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse lectus dolor, interdum elementum fringilla et, efficitur a libero. Etiam sit amet imperdiet nunc. Sed viverra magna vel lorem euismod, nec interdum lectus volutpat. Vestibulum lobortis non ex quis sagittis. Nunc volutpat eleifend tincidunt. Maecenas at imperdiet libero. Sed vulputate ligula in turpis suscipit gravida. Nam sit amet ornare mi. Donec fermentum aliquam arcu id ullamcorper. Nam sodales quis mi non lobortis.

            Quisque dictum purus ac eros scelerisque, et pulvinar ex sollicitudin. Nullam sit amet turpis felis. Sed dictum enim a ipsum fringilla sagittis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi sagittis facilisis orci et ullamcorper. Aenean hendrerit massa non lacus posuere dapibus. Curabitur vel placerat augue. Integer efficitur elit nec urna ornare tempor. Nullam eu rutrum lacus. Mauris porta tempus fermentum. Sed tristique lorem quis ipsum tempor dapibus. Cras quis nisi massa. Suspendisse ut sapien sollicitudin, laoreet sem ut, convallis mi.

            Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse sit amet ipsum non nisl laoreet facilisis. Nulla facilisi. Sed quis tristique eros. Proin sed tempor nulla. Nulla blandit facilisis tellus id pulvinar. Vivamus vel imperdiet dui, iaculis ultricies sapien.

            Duis finibus purus a enim consequat, nec vestibulum elit viverra. Quisque porta semper tellus, et tempus urna tincidunt sed. Fusce finibus congue sem, sed egestas dolor. Sed molestie magna vel turpis euismod ullamcorper. Nulla facilisis scelerisque lectus sit amet porttitor. Aenean elementum vehicula neque. In et nulla ac eros mattis ullamcorper sed non turpis. In convallis enim sed maximus molestie.
            </p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis venenatis nisi, eget hendrerit urna. In sollicitudin commodo ipsum, nec suscipit felis maximus nec. Sed maximus, odio quis ultrices volutpat, felis mauris varius magna, ac consectetur tellus lorem ut tortor. Aenean a nisl quis ex auctor elementum sit amet ac erat. Ut aliquam augue vitae vulputate dictum. Aliquam mauris nulla, fringilla ac erat at, lacinia tempor ipsum. Nam blandit cursus magna, ac sodales risus tristique vitae. Proin hendrerit, lorem ac placerat aliquam, arcu ligula tristique ante, eu volutpat eros nisi ac quam. Morbi dui tortor, ultrices quis tempus et, ultricies non enim. Nullam sit amet ante in purus iaculis consectetur. Suspendisse id ipsum accumsan, vestibulum mauris vitae, mollis nisl. Quisque id justo tincidunt, commodo quam vel, vestibulum tortor. Nunc ipsum ante, posuere eu vulputate vel, varius sed massa. Ut a orci scelerisque, ornare magna id, faucibus arcu. Maecenas vitae ex lorem. Nam a nibh id ipsum vestibulum dapibus.

            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer nec porttitor ante. Proin vitae faucibus velit, in sollicitudin libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse lectus dolor, interdum elementum fringilla et, efficitur a libero. Etiam sit amet imperdiet nunc. Sed viverra magna vel lorem euismod, nec interdum lectus volutpat. Vestibulum lobortis non ex quis sagittis. Nunc volutpat eleifend tincidunt. Maecenas at imperdiet libero. Sed vulputate ligula in turpis suscipit gravida. Nam sit amet ornare mi. Donec fermentum aliquam arcu id ullamcorper. Nam sodales quis mi non lobortis.

            Quisque dictum purus ac eros scelerisque, et pulvinar ex sollicitudin. Nullam sit amet turpis felis. Sed dictum enim a ipsum fringilla sagittis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi sagittis facilisis orci et ullamcorper. Aenean hendrerit massa non lacus posuere dapibus. Curabitur vel placerat augue. Integer efficitur elit nec urna ornare tempor. Nullam eu rutrum lacus. Mauris porta tempus fermentum. Sed tristique lorem quis ipsum tempor dapibus. Cras quis nisi massa. Suspendisse ut sapien sollicitudin, laoreet sem ut, convallis mi.

            Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse sit amet ipsum non nisl laoreet facilisis. Nulla facilisi. Sed quis tristique eros. Proin sed tempor nulla. Nulla blandit facilisis tellus id pulvinar. Vivamus vel imperdiet dui, iaculis ultricies sapien.

            Duis finibus purus a enim consequat, nec vestibulum elit viverra. Quisque porta semper tellus, et tempus urna tincidunt sed. Fusce finibus congue sem, sed egestas dolor. Sed molestie magna vel turpis euismod ullamcorper. Nulla facilisis scelerisque lectus sit amet porttitor. Aenean elementum vehicula neque. In et nulla ac eros mattis ullamcorper sed non turpis. In convallis enim sed maximus molestie.
            </p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis venenatis nisi, eget hendrerit urna. In sollicitudin commodo ipsum, nec suscipit felis maximus nec. Sed maximus, odio quis ultrices volutpat, felis mauris varius magna, ac consectetur tellus lorem ut tortor. Aenean a nisl quis ex auctor elementum sit amet ac erat. Ut aliquam augue vitae vulputate dictum. Aliquam mauris nulla, fringilla ac erat at, lacinia tempor ipsum. Nam blandit cursus magna, ac sodales risus tristique vitae. Proin hendrerit, lorem ac placerat aliquam, arcu ligula tristique ante, eu volutpat eros nisi ac quam. Morbi dui tortor, ultrices quis tempus et, ultricies non enim. Nullam sit amet ante in purus iaculis consectetur. Suspendisse id ipsum accumsan, vestibulum mauris vitae, mollis nisl. Quisque id justo tincidunt, commodo quam vel, vestibulum tortor. Nunc ipsum ante, posuere eu vulputate vel, varius sed massa. Ut a orci scelerisque, ornare magna id, faucibus arcu. Maecenas vitae ex lorem. Nam a nibh id ipsum vestibulum dapibus.

            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer nec porttitor ante. Proin vitae faucibus velit, in sollicitudin libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse lectus dolor, interdum elementum fringilla et, efficitur a libero. Etiam sit amet imperdiet nunc. Sed viverra magna vel lorem euismod, nec interdum lectus volutpat. Vestibulum lobortis non ex quis sagittis. Nunc volutpat eleifend tincidunt. Maecenas at imperdiet libero. Sed vulputate ligula in turpis suscipit gravida. Nam sit amet ornare mi. Donec fermentum aliquam arcu id ullamcorper. Nam sodales quis mi non lobortis.

            Quisque dictum purus ac eros scelerisque, et pulvinar ex sollicitudin. Nullam sit amet turpis felis. Sed dictum enim a ipsum fringilla sagittis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi sagittis facilisis orci et ullamcorper. Aenean hendrerit massa non lacus posuere dapibus. Curabitur vel placerat augue. Integer efficitur elit nec urna ornare tempor. Nullam eu rutrum lacus. Mauris porta tempus fermentum. Sed tristique lorem quis ipsum tempor dapibus. Cras quis nisi massa. Suspendisse ut sapien sollicitudin, laoreet sem ut, convallis mi.

            Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse sit amet ipsum non nisl laoreet facilisis. Nulla facilisi. Sed quis tristique eros. Proin sed tempor nulla. Nulla blandit facilisis tellus id pulvinar. Vivamus vel imperdiet dui, iaculis ultricies sapien.

            Duis finibus purus a enim consequat, nec vestibulum elit viverra. Quisque porta semper tellus, et tempus urna tincidunt sed. Fusce finibus congue sem, sed egestas dolor. Sed molestie magna vel turpis euismod ullamcorper. Nulla facilisis scelerisque lectus sit amet porttitor. Aenean elementum vehicula neque. In et nulla ac eros mattis ullamcorper sed non turpis. In convallis enim sed maximus molestie.
            </p>
            <button onClick={handleAboutClick}>Back to the top</button>
        </div>
    )
}

export default About

